# Generated by Django 3.2.10 on 2022-01-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project_scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], null=True, verbose_name='وضعیت')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_Project', to='Project.project', verbose_name='نام پروژه')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'نام پروژه',
                'verbose_name_plural': 'لیست زمانبندی پروژه',
            },
        ),
    ]
