# Generated by Django 3.2.9 on 2021-12-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0003_auto_20211226_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_scheduling_ScrumMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], verbose_name='وضعیت')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='نام پروژه')),
                ('user_id', models.ForeignKey(limit_choices_to={'Project_id': 'project_id'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'زمانبندی مدیر پروژه',
                'verbose_name_plural': 'لیست زمانبندی',
            },
        ),
        migrations.CreateModel(
            name='add_scheduling_Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], verbose_name='وضعیت')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='نام پروژه')),
                ('user_id', models.ForeignKey(limit_choices_to={'Project_id': 'project_id'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'زمانبندی کارشناس',
                'verbose_name_plural': 'لیست زمانبندی کارشناس',
            },
        ),
    ]
