# Generated by Django 3.2.10 on 2022-01-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_scheduling',
            options={'verbose_name': 'نام پروژه', 'verbose_name_plural': 'لیست زمانبندی پروژه  '},
        ),
    ]
