# Generated by Django 3.2.9 on 2021-12-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20211226_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
            options={
                'verbose_name': 'زمانبندی پروژه',
                'verbose_name_plural': 'لیست زمانبندی پروژه',
            },
        ),
        migrations.CreateModel(
            name='scheduling_Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], verbose_name='وضعیت')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='نام پروژه')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'زمانبندی کارشناس',
                'verbose_name_plural': 'لیست زمانبندی کارشناس',
            },
        ),
        migrations.CreateModel(
            name='scheduling_ScrumMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], verbose_name='وضعیت')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_Project', to='Project.project', verbose_name='نام پروژه')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر')),
            ],
            options={
                'verbose_name': 'زمانبندی مدیر پروژه',
                'verbose_name_plural': 'لیست زمانبندی مدیر پروژه',
            },
        ),
        migrations.RemoveField(
            model_name='add_scheduling_scrummaster',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='add_scheduling_scrummaster',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='add_scheduling_Expert',
        ),
        migrations.DeleteModel(
            name='add_scheduling_ScrumMaster',
        ),
        migrations.AddField(
            model_name='project_scheduling',
            name='scheduling_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduling.scheduling_scrummaster'),
        ),
    ]
