# Generated by Django 3.2.9 on 2021-12-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20211226_1228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Scheduling', '0002_auto_20211226_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling_scrummaster',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='scheduling_scrummaster',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='project_scheduling',
            options={'verbose_name': 'نام پروژه', 'verbose_name_plural': 'لیست زمانبندی پروژه'},
        ),
        migrations.RemoveField(
            model_name='project_scheduling',
            name='scheduling_id',
        ),
        migrations.AddField(
            model_name='project_scheduling',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_Project', to='Project.project', verbose_name='نام پروژه'),
        ),
        migrations.AddField(
            model_name='project_scheduling',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'DeActive')], null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='project_scheduling',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر'),
        ),
        migrations.DeleteModel(
            name='scheduling_Expert',
        ),
        migrations.DeleteModel(
            name='scheduling_ScrumMaster',
        ),
    ]
