# Generated by Django 3.2.10 on 2022-02-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': ' اعتبار سنجی', 'verbose_name_plural': 'اعتبار سنجی ها'},
        ),
    ]
