# Generated by Django 3.2.10 on 2022-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_validation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.CharField(max_length=5000, verbose_name='کد'),
        ),
    ]
