# Generated by Django 3.2.9 on 2021-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='takhasos',
            field=models.IntegerField(choices=[(1, 'expert'), (2, 'scram'), (3, 'fonshial')], default=1),
        ),
    ]
