# Generated by Django 3.2.10 on 2022-01-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0002_myuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Expert',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Financial',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='ScrumMaster',
        ),
    ]
