# Generated by Django 3.2.9 on 2021-12-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0002_user_takhasos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='takhasos',
            new_name='Skill',
        ),
    ]
