# Generated by Django 3.2.9 on 2021-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0004_auto_20211213_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Skill',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Role',
            field=models.IntegerField(choices=[(1, 'Expert'), (2, 'ScrumMaster'), (3, 'Financial'), (4, 'Admin')], default=1),
        ),
    ]
