# Generated by Django 3.2.10 on 2022-01-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0004_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project/images', verbose_name='عکس'),
        ),
    ]
