# Generated by Django 3.2.9 on 2021-12-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0005_auto_20211214_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'لیست کاربران'},
        ),
    ]
