# Generated by Django 3.2.9 on 2021-12-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0006_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'لیست کاربران '},
        ),
    ]
