# Generated by Django 3.2.9 on 2021-12-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddUser', '0007_alter_myuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='Role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='Admin',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Expert',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Financial',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='ScrumMaster',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
