# Generated by Django 3.2.9 on 2021-12-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20211214_1424'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial',
            options={'verbose_name': 'مالی', 'verbose_name_plural': 'لیست مالی'},
        ),
        migrations.AlterField(
            model_name='financial',
            name='Date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='Description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='money',
            field=models.IntegerField(verbose_name='پول'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='ایدی پروژه'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='userMoneydepositor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='userRecipientofmoney',
            field=models.ManyToManyField(related_name='userMoneydepositor', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده'),
        ),
    ]
