# Generated by Django 3.2.9 on 2021-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0002_auto_20211215_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='Date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ واریز'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='money',
            field=models.CharField(max_length=50, verbose_name='پول'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='type',
            field=models.IntegerField(choices=[(1, 'واریز '), (2, ' برداشت')], verbose_name='نوع'),
        ),
    ]
