# Generated by Django 3.2.10 on 2022-01-06 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Financial', '0003_auto_20211215_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='image',
            field=models.ImageField(null=True, upload_to='financial/images', verbose_name='عکس'),
        ),
        migrations.RemoveField(
            model_name='financial',
            name='userMoneydepositor',
        ),
        migrations.AddField(
            model_name='financial',
            name='userMoneydepositor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده'),
        ),
        migrations.RemoveField(
            model_name='financial',
            name='userRecipientofmoney',
        ),
        migrations.AddField(
            model_name='financial',
            name='userRecipientofmoney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userMoneydepositor', to=settings.AUTH_USER_MODEL, verbose_name='دریافت کننده'),
        ),
    ]
