# Generated by Django 3.2.10 on 2022-01-29 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'والد',
                'verbose_name_plural': 'لیست والد ها',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان')),
                ('priority', models.IntegerField(verbose_name='اولویت')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.step', verbose_name='والد')),
                ('projectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Project.project', verbose_name='ایدی پروژه')),
            ],
            options={
                'verbose_name': 'مرحله',
                'verbose_name_plural': 'لیست مراحل',
            },
        ),
    ]
