# Generated by Django 3.2.9 on 2021-12-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(choices=[(1, 'high'), (2, 'normal'), (3, 'low')], default=2)),
                ('ParentId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.parent')),
                ('ProjectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
    ]
