# Generated by Django 3.2.9 on 2021-12-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20211214_1424'),
        ('Step', '0002_alter_step_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'مرحله', 'verbose_name_plural': 'لیست مراحل'},
        ),
        migrations.AlterField(
            model_name='parent',
            name='parentname',
            field=models.CharField(max_length=50, verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='step',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='step',
            name='ParentId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.parent', verbose_name='ایدی والد'),
        ),
        migrations.AlterField(
            model_name='step',
            name='ProjectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project', verbose_name='ایدی پروژه'),
        ),
        migrations.AlterField(
            model_name='step',
            name='priority',
            field=models.IntegerField(verbose_name='اولویت'),
        ),
    ]
