# Generated by Django 3.2.9 on 2021-12-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Step', '0003_auto_20211215_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'والد', 'verbose_name_plural': 'لیست والد ها'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='ParentId',
        ),
        migrations.AddField(
            model_name='step',
            name='Parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.parent', verbose_name='ایدی والد'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parentname',
            field=models.CharField(max_length=50, verbose_name='نام والد'),
        ),
    ]
