# Generated by Django 3.2.10 on 2022-01-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20220107_0011'),
        ('Step', '0004_auto_20211215_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parentname',
        ),
        migrations.RemoveField(
            model_name='step',
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='step',
            name='ProjectId',
        ),
        migrations.AddField(
            model_name='step',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.step', verbose_name='والد'),
        ),
        migrations.AddField(
            model_name='step',
            name='projectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Project.project', verbose_name='ایدی پروژه'),
        ),
    ]
