# Generated by Django 3.2.10 on 2022-01-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'deActive'), (1, 'Active'), (2, 'Fail'), (3, 'Done')], default=0, editable=False, null=True, verbose_name='وضعیت')),
                ('periority', models.IntegerField(choices=[(1, 'high'), (2, 'normal'), (3, 'low')], default=3, verbose_name='الویت')),
                ('ratePerformance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], editable=False, null=True, verbose_name='امتیاز')),
                ('doneDate', models.DateField(auto_now_add=True)),
                ('estimated_end', models.DateField(blank=True, editable=False, null=True, verbose_name='پایان تخمینی')),
                ('category', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Project.category', verbose_name='دسته بندی')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskCreates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
            ],
            options={
                'verbose_name': 'تسک',
                'verbose_name_plural': 'لیست تسک ها',
            },
        ),
    ]
