# Generated by Django 3.2.9 on 2021-12-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Step', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferst_neme', models.TextField()),
                ('last_name', models.TextField()),
                ('emailaddres', models.EmailField(max_length=254)),
                ('Role', models.IntegerField(choices=[(1, 'SEO'), (2, 'FRONT_END'), (3, 'BACK_END'), (4, 'SRVER')])),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('createDate', models.DateField(null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'deActive'), (1, 'Active'), (2, 'Faile')], default=0, null=True)),
                ('ratePerformance', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('periority', models.IntegerField(choices=[(1, 'high'), (2, 'normal'), (3, 'low')], default=3)),
                ('Expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('StepID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.step')),
            ],
        ),
    ]
