# Generated by Django 3.2.9 on 2021-12-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Expert',
        ),
    ]
