# Generated by Django 3.2.9 on 2021-12-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20211211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ratePerformance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'deActive'), (1, 'Active'), (2, 'Faile'), (3, 'Done')], default=0, null=True),
        ),
    ]
