# Generated by Django 3.2.9 on 2021-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_auto_20211212_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='startDate',
        ),
        migrations.AlterField(
            model_name='task',
            name='Estimated_end',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'deActive'), (1, 'Active'), (2, 'Faile'), (3, 'Done')], default=0, editable=False, null=True),
        ),
    ]
