# Generated by Django 3.2.9 on 2021-12-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Step', '0003_auto_20211215_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0007_auto_20211214_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'تسک', 'verbose_name_plural': 'لیست تسک ها'},
        ),
        migrations.AlterField(
            model_name='task',
            name='Estimated_end',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='پایان تخمینی'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AlterField(
            model_name='task',
            name='StepID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Step.step', verbose_name='شناسه مرحله'),
        ),
        migrations.AlterField(
            model_name='task',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='task',
            name='periority',
            field=models.IntegerField(choices=[(1, 'high'), (2, 'normal'), (3, 'low')], default=3, verbose_name='الویت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ratePerformance',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], editable=False, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'deActive'), (1, 'Active'), (2, 'Faile'), (3, 'Done')], default=0, editable=False, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
