# Generated by Django 3.2.10 on 2022-01-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Step', '0005_auto_20220107_0011'),
        ('Task', '0008_auto_20211215_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Estimated_end',
            new_name='estimated_end',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Expert',
            new_name='expert',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StepID',
        ),
        migrations.AddField(
            model_name='task',
            name='stepId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Step.step', verbose_name='شناسه مرحله'),
        ),
    ]
