# Generated by Django 3.2.10 on 2022-01-26 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام بخش')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Project.sections', verbose_name='زیرمجموعه')),
            ],
            options={
                'verbose_name': 'بخش ',
                'verbose_name_plural': 'بخش ها ',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(null=True, upload_to='project/images', verbose_name='عکس')),
                ('startDate', models.DateField(verbose_name='زمان شروع')),
                ('endDate', models.DateField(verbose_name='زمان پایان')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Done'), (2, 'deActive'), (3, 'Active'), (4, 'Fail')], default=2, null=True, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectCreates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('experts', models.ManyToManyField(limit_choices_to={'groups__id': 1}, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ها')),
                ('scrumMaster', models.ManyToManyField(limit_choices_to={'groups__id': 2}, related_name='scrumasterProjects', to=settings.AUTH_USER_MODEL, verbose_name='اسکرام مستر')),
                ('sections', models.ManyToManyField(related_name='projects', to='Project.Sections', verbose_name='بخش ها')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'لیست پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('status', models.IntegerField(choices=[(0, 'Enable'), (1, 'Disable')], default=0, editable=False, verbose_name='وضعیت')),
                ('weight', models.IntegerField(verbose_name='وزن')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Project.project', verbose_name='شناسه پروژه')),
                ('section_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Project.sections', verbose_name='شناسه بخش')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی ها ',
            },
        ),
    ]
