# Generated by Django 3.2.9 on 2021-12-14 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'پروژه', 'verbose_name_plural': 'لیست پروژه ها'},
        ),
        migrations.AlterField(
            model_name='project',
            name='Experts',
            field=models.ManyToManyField(related_name='creator_set', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ها'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ScrumMaster',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='اسکرام مستر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'deActive'), (3, 'Active'), (4, 'Fail')], default=2, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
