# Generated by Django 3.2.9 on 2021-12-26 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0002_auto_20211214_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Experts',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Expert'}, related_name='creator_set', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ها'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ScrumMaster',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'ScrumMaster'}, to=settings.AUTH_USER_MODEL, verbose_name='اسکرام مستر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Done'), (2, 'deActive'), (3, 'Active'), (4, 'Fail')], default=2, null=True, verbose_name='وضعیت'),
        ),
    ]
