# Generated by Django 3.2.10 on 2022-01-06 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0003_auto_20211226_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Experts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ScrumMaster',
        ),
        migrations.AddField(
            model_name='project',
            name='experts',
            field=models.ManyToManyField(limit_choices_to={'groups__id': 1}, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس ها'),
        ),
        migrations.AddField(
            model_name='project',
            name='scrumMaster',
            field=models.ManyToManyField(limit_choices_to={'groups__id': 2}, related_name='scrumasterProjects', to=settings.AUTH_USER_MODEL, verbose_name='اسکرام مستر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='project/images', verbose_name='عکس'),
        ),
    ]
