# Generated by Django 3.2.10 on 2022-01-07 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0004_auto_20220107_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectCreates', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
    ]
