# Generated by Django 3.2.10 on 2022-01-07 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
